### ISSUE TITLE
Logging bucket generates a name with a duplicate

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/terraform-aws-tfstate-backend#106]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Turning on the logging bucket creates a bucket named: `nmspc-as1-root-nmspc-as1-root-tfstate-logs`.

## Expected Behavior

A name like: `nmspc-as1-root-tfstate-logs`.

## Steps to Reproduce

```hcl
module "tfstate_backend" {
  source  = "cloudposse/tfstate-backend/aws"
  version = "0.38.0"

  enable_server_side_encryption = var.enable_server_side_encryption
  force_destroy                 = var.force_destroy
  logging_bucket_enabled        = true
  prevent_unencrypted_uploads   = var.prevent_unencrypted_uploads

  context = module.this.context
}
```

## Screenshots

N/A

## Environment (please complete the following information):

All envs are impacted starting with v0.38.0.

## Additional Context

Culprit: #104

**Comment by lmf-mx** [comment]
The pattern I'm seeing attempted to create a bucket name with is `[namespace]-[environment]-[state]-[namespace]-[environment]-[state]-[name]-[attributes]-logs-[attributes]`.
I suspect something is happening in the s3-log-storage module.

**Comment by nitrocode** [comment]
Hmm, most likely because we override the `name` with a full `label` module's `id`

https://github.com/cloudposse/terraform-aws-tfstate-backend/blob/107da1504b7e7fd32a536cfae59602d67d654b39/main.tf#L150

so the example name `nmspc-as1-root-nmspc-as1-root-tfstate-logs`

Follows the format `[name]-[environment]-[stage]-[attributes]-logs` where the `name` is `nmspc-as1-root-nmspc`

**Comment by ericluria** [comment]
I think the issue is that both parameters `name` and `context` are provided to the `cloudposse/s3-log-storage/aws` module [here](https://github.com/cloudposse/terraform-aws-tfstate-backend/blob/107da1504b7e7fd32a536cfae59602d67d654b39/main.tf#L150-L153). Removing the `context` parameter and only providing the name should fix the issue.

**Comment by Nuru** [comment]
This is an example of one reason why we are moving away from creating supporting resources (like a log bucket) inside the module. This will be removed in the next major release.
