### ISSUE TITLE
Make use of templatefile Function

### ISSUE THREAD

**Issue by x80486** [cloudposse/terraform-aws-tfstate-backend#34]
Since you require Terraform `0.12.x`, I think it's better to use the [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html) function instead.

---

...and you've got `100` stars :tada:

**Comment by dictvm** [comment]
Some additional context: This module depends on the `hashicorp/template` provider. Since the `template` provider has been [deprecated and archived](https://registry.terraform.io/providers/hashicorp/template/latest) it was never built for ARM64 devices such as Apple's M1 Macs, leading to the following error upon running `terraform init`: 

```
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
````

A quick fix is to build it yourself, which is described [here](https://github.com/hashicorp/terraform/issues/27257#issuecomment-825102330).
